<?php

namespace BiblioBundle\Repository;

/**
 * enfantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class enfantsRepository extends \Doctrine\ORM\EntityRepository
{
}
